# Generated by Django 6.0 on 2026-03-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobpost_structured_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
