# Generated by Django 5.2.8 on 2026-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='key_responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
