# Generated by Django 5.2.8 on 2026-03-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_jobpost_key_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsresult',
            name='custom_job_title',
            field=models.CharField(blank=True, help_text='Used for quick scans without a formal job post', max_length=255),
        ),
        migrations.AlterField(
            model_name='atsresult',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_results', to='core.jobpost'),
        ),
    ]
