# Generated by Django 5.2.8 on 2026-04-01 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skill_skill_type_certificate_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume_name',
            field=models.CharField(default='My Resume', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
