# Generated by Django 5.2.8 on 2026-04-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobseekerprofile_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume_name',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='education_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tools_and_technologies',
            field=models.TextField(blank=True, help_text='Specific tools or software'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
