# Generated by Django 5.2.8 on 2026-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_jobseekerprofile_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsresult',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
