# Generated by Django 5.2.8 on 2026-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atsresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal notes for administrators.', null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Disabled', 'Disabled')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('hr', 'HR'), ('admin', 'Admin')], default='jobseeker', max_length=20),
        ),
    ]
