# Generated by Django 5.2.8 on 2026-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobpost_admin_note_alter_jobpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for applications', null=True),
        ),
    ]
