# Generated by Django 5.2.8 on 2026-04-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_jobpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsresult',
            name='score_breakdown',
            field=models.TextField(blank=True, help_text='JSON storage for weighted score pillars'),
        ),
        migrations.AddField(
            model_name='parsedresumedata',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresumedata',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresumedata',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
