# Generated by Django 5.2.8 on 2026-04-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_atsresult_score_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='latest_score',
            field=models.FloatField(default=0),
        ),
    ]
