# Generated by Django 5.2.8 on 2026-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resume_latest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Professional Title / Job Title', max_length=120),
        ),
    ]
