# Generated by Django 5.2.8 on 2026-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobseekerprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
