# Generated by Django 5.2.8 on 2026-04-12 14:59

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.utils.OverwriteStorage(), upload_to='profile_pics/'),
        ),
    ]
